spring.application.name=ticket-booking-ticket-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_booking_ticket
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true